package com.gps21.model;

// Generated Mar 16, 2017 3:16:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Maintenances generated by hbm2java
 */
@Entity
@Table(name = "maintenances", catalog = "traccar")
public class Maintenances implements java.io.Serializable {

	private Long id;
	private Devices devices;
	private int indexNo;
	private double lastService;
	private String name;
	private double serviceInterval;
	private Set<Events> eventses = new HashSet<Events>(0);

	public Maintenances() {
	}

	public Maintenances(int indexNo, double lastService, double serviceInterval) {
		this.indexNo = indexNo;
		this.lastService = lastService;
		this.serviceInterval = serviceInterval;
	}

	public Maintenances(Devices devices, int indexNo, double lastService,
			String name, double serviceInterval, Set<Events> eventses) {
		this.devices = devices;
		this.indexNo = indexNo;
		this.lastService = lastService;
		this.name = name;
		this.serviceInterval = serviceInterval;
		this.eventses = eventses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id")
	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	@Column(name = "indexNo", nullable = false)
	public int getIndexNo() {
		return this.indexNo;
	}

	public void setIndexNo(int indexNo) {
		this.indexNo = indexNo;
	}

	@Column(name = "lastService", nullable = false, precision = 22, scale = 0)
	public double getLastService() {
		return this.lastService;
	}

	public void setLastService(double lastService) {
		this.lastService = lastService;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "serviceInterval", nullable = false, precision = 22, scale = 0)
	public double getServiceInterval() {
		return this.serviceInterval;
	}

	public void setServiceInterval(double serviceInterval) {
		this.serviceInterval = serviceInterval;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maintenances")
	public Set<Events> getEventses() {
		return this.eventses;
	}

	public void setEventses(Set<Events> eventses) {
		this.eventses = eventses;
	}

}
