package com.gps21.model;

// Generated Mar 16, 2017 3:16:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sensors generated by hbm2java
 */
@Entity
@Table(name = "sensors", catalog = "traccar")
public class Sensors implements java.io.Serializable {

	private Long id;
	private Devices devices;
	private String description;
	private String intervals;
	private String name;
	private String parameterName;
	private boolean visible;

	public Sensors() {
	}

	public Sensors(boolean visible) {
		this.visible = visible;
	}

	public Sensors(Devices devices, String description, String intervals,
			String name, String parameterName, boolean visible) {
		this.devices = devices;
		this.description = description;
		this.intervals = intervals;
		this.name = name;
		this.parameterName = parameterName;
		this.visible = visible;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id")
	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "intervals", length = 2048)
	public String getIntervals() {
		return this.intervals;
	}

	public void setIntervals(String intervals) {
		this.intervals = intervals;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "parameterName")
	public String getParameterName() {
		return this.parameterName;
	}

	public void setParameterName(String parameterName) {
		this.parameterName = parameterName;
	}

	@Column(name = "visible", nullable = false)
	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

}
