package com.gps21.model;

// Generated Mar 16, 2017 3:16:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NotificationTemplates generated by hbm2java
 */
@Entity
@Table(name = "notification_templates", catalog = "traccar")
public class NotificationTemplates implements java.io.Serializable {

	private Long id;
	private NotificationSettings notificationSettings;
	private String body;
	private String contentType;
	private String subject;
	private String type;

	public NotificationTemplates() {
	}

	public NotificationTemplates(NotificationSettings notificationSettings,
			String body, String contentType, String subject, String type) {
		this.notificationSettings = notificationSettings;
		this.body = body;
		this.contentType = contentType;
		this.subject = subject;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "settings_id")
	public NotificationSettings getNotificationSettings() {
		return this.notificationSettings;
	}

	public void setNotificationSettings(
			NotificationSettings notificationSettings) {
		this.notificationSettings = notificationSettings;
	}

	@Column(name = "body", length = 4096)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "contentType")
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "subject")
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "type")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
