package com.gps21.model;

// Generated Mar 16, 2017 3:16:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NotificationSettings generated by hbm2java
 */
@Entity
@Table(name = "notification_settings", catalog = "traccar")
public class NotificationSettings implements java.io.Serializable {

	private Long id;
	private Users users;
	private String fromAddress;
	private String password;
	private int port;
	private String pushbulletAccessToken;
	private String secureConnectionType;
	private String server;
	private boolean useAuthorization;
	private String username;
	private Set<NotificationTemplates> notificationTemplateses = new HashSet<NotificationTemplates>(
			0);

	public NotificationSettings() {
	}

	public NotificationSettings(int port, boolean useAuthorization) {
		this.port = port;
		this.useAuthorization = useAuthorization;
	}

	public NotificationSettings(Users users, String fromAddress,
			String password, int port, String pushbulletAccessToken,
			String secureConnectionType, String server,
			boolean useAuthorization, String username,
			Set<NotificationTemplates> notificationTemplateses) {
		this.users = users;
		this.fromAddress = fromAddress;
		this.password = password;
		this.port = port;
		this.pushbulletAccessToken = pushbulletAccessToken;
		this.secureConnectionType = secureConnectionType;
		this.server = server;
		this.useAuthorization = useAuthorization;
		this.username = username;
		this.notificationTemplateses = notificationTemplateses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "fromAddress")
	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "port", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	@Column(name = "pushbulletAccessToken")
	public String getPushbulletAccessToken() {
		return this.pushbulletAccessToken;
	}

	public void setPushbulletAccessToken(String pushbulletAccessToken) {
		this.pushbulletAccessToken = pushbulletAccessToken;
	}

	@Column(name = "secureConnectionType")
	public String getSecureConnectionType() {
		return this.secureConnectionType;
	}

	public void setSecureConnectionType(String secureConnectionType) {
		this.secureConnectionType = secureConnectionType;
	}

	@Column(name = "server")
	public String getServer() {
		return this.server;
	}

	public void setServer(String server) {
		this.server = server;
	}

	@Column(name = "useAuthorization", nullable = false)
	public boolean isUseAuthorization() {
		return this.useAuthorization;
	}

	public void setUseAuthorization(boolean useAuthorization) {
		this.useAuthorization = useAuthorization;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationSettings")
	public Set<NotificationTemplates> getNotificationTemplateses() {
		return this.notificationTemplateses;
	}

	public void setNotificationTemplateses(
			Set<NotificationTemplates> notificationTemplateses) {
		this.notificationTemplateses = notificationTemplateses;
	}

}
