package com.gps21.model;

// Generated Mar 16, 2017 3:16:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Positions generated by hbm2java
 */
@Entity
@NamedQuery(name="Device.id",query="select p.id from Devices d  join d.positions p where d.name =:devicename")
@Table(name = "positions", catalog = "traccar")
public class Positions implements java.io.Serializable {

	private Long id;
	private Devices devices;
	private String address;
	private Double altitude;
	private Double course;
	private Double latitude;
	private Double longitude;
	private String other;
	private Double power;
	private String protocol;
	private Date serverTime;
	private Double speed;
	private Date time;
	private Boolean valid;
	private Set<Events> eventses = new HashSet<Events>(0);
	private Set<Devices> deviceses = new HashSet<Devices>(0);

	public Positions() {
	}

	public Positions(Devices devices, String address, Double altitude,
			Double course, Double latitude, Double longitude, String other,
			Double power, String protocol, Date serverTime, Double speed,
			Date time, Boolean valid, Set<Events> eventses,
			Set<Devices> deviceses) {
		this.devices = devices;
		this.address = address;
		this.altitude = altitude;
		this.course = course;
		this.latitude = latitude;
		this.longitude = longitude;
		this.other = other;
		this.power = power;
		this.protocol = protocol;
		this.serverTime = serverTime;
		this.speed = speed;
		this.time = time;
		this.valid = valid;
		this.eventses = eventses;
		this.deviceses = deviceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id")
	public Devices getDevices() {
		return this.devices;
	}

	public void setDevices(Devices devices) {
		this.devices = devices;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "altitude", precision = 22, scale = 0)
	public Double getAltitude() {
		return this.altitude;
	}

	public void setAltitude(Double altitude) {
		this.altitude = altitude;
	}

	@Column(name = "course", precision = 22, scale = 0)
	public Double getCourse() {
		return this.course;
	}

	public void setCourse(Double course) {
		this.course = course;
	}

	@Column(name = "latitude", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 22, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "other", length = 2048)
	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	@Column(name = "power", precision = 22, scale = 0)
	public Double getPower() {
		return this.power;
	}

	public void setPower(Double power) {
		this.power = power;
	}

	@Column(name = "protocol")
	public String getProtocol() {
		return this.protocol;
	}

	public void setProtocol(String protocol) {
		this.protocol = protocol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "serverTime", length = 19)
	public Date getServerTime() {
		return this.serverTime;
	}

	public void setServerTime(Date serverTime) {
		this.serverTime = serverTime;
	}

	@Column(name = "speed", precision = 22, scale = 0)
	public Double getSpeed() {
		return this.speed;
	}

	public void setSpeed(Double speed) {
		this.speed = speed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "valid")
	public Boolean getValid() {
		return this.valid;
	}

	public void setValid(Boolean valid) {
		this.valid = valid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "positions")
	public Set<Events> getEventses() {
		return this.eventses;
	}

	public void setEventses(Set<Events> eventses) {
		this.eventses = eventses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "positions")
	public Set<Devices> getDeviceses() {
		return this.deviceses;
	}

	public void setDeviceses(Set<Devices> deviceses) {
		this.deviceses = deviceses;
	}

}
